name: Feature
description: Request a new feature or functionality
type: feature
body:
  - type: input
    id: title
    attributes:
      label: Feature Name
      description: Short title of the feature
      placeholder: e.g. Smart Node Linking
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should this feature do and why?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define what "done" means for this feature
      placeholder: |
        - [ ] API endpoint is implemented
        - [ ] Unit tests are written
        - [ ] Integrated into main workflow
        - [ ] Verified in dev environment