name: Build and Push Docker Image (Main)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image tags
        id: prepare
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_BASE=ghcr.io/${{ github.repository }}/keystone

          echo "short_tag=${IMAGE_BASE}:${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "latest_tag=${IMAGE_BASE}:latest" >> $GITHUB_OUTPUT

      - name: Build Docker image with both tags
        run: |
          docker build -t ${{ steps.prepare.outputs.short_tag }} -t ${{ steps.prepare.outputs.latest_tag }} .

      - name: Push both tags to GHCR
        run: |
          docker push ${{ steps.prepare.outputs.short_tag }}
          docker push ${{ steps.prepare.outputs.latest_tag }}
